### ISSUE TITLE
peer review

### ISSUE THREAD

**Issue by RowinRuizendaal** [StanBankras/progressive-web-apps-2021#1]
### Code review

> Cool om te zien dat je typescript gebruikt, voor mij ook eens interessant om te zien!

Code is zeer netjes opgesplitst in verschillende modules/mappen, hierdoor is het overzicht wat mij betreft heel overzichtelijk.

### Kleine opmerking(en)

in footer.ejs gebruik je:

```html
</div>
    </main>
    <footer>
      <p>Powered by</p>
      <img src="/img/coinpaprika-logo.svg" alt="coinpaprika-logo">
    </footer>
  </body>
</html>
```

Het kan misschien verwarrend zijn dat de footer en een div afsluit en de main omdat je verwacht dat hier alleen het footer element zou staan:

```html
    <footer>
      <p>Powered by</p>
      <img src="/img/coinpaprika-logo.svg" alt="coinpaprika-logo">
    </footer>
```
    
Misschien is dat iets om mee te nemen om het nog iets overzichtelijker te houden in je DOM :), het zelde geldt eigenlijk voor je header.ejs hier open je de main en daaronder weer een div met een class van container, misschien kan je een andere partial maken voor die container? (het is een suggestie :))

Voor de rest heb ik niet echt iets op te merken. (☞ﾟヮﾟ)☞

**Comment by standrd** [comment]
Thanks voor de suggestie, ben het inderdaad met je eens dat die afsluiting van de div in de footer het niet heel erg modulair maakt. Dit ga ik zeker oplossen!
