### ISSUE TITLE
Code review week 1

### ISSUE THREAD

**Issue by RobinFrugte97** [StanBankras/progressive-web-apps-2021#2]
Yo Stan,

Goed dat je je site al hebt gedeployt! 

In je readme staan al een aantal packages die je gebruikt bij je resources. Goed begin, misschien kun je ergens anders nog beschrijven wat ze voor je doen en waarom je ze gebruikt. Hetzelfde geldt voor je script chain. Je hebt al een aantal scripts die een kleine chain vormen, beschrijf wat het doet in je readme.

Je werkt server-side al met modules, maar ik denk dat je een deel van je code nog in aparte modules kan zetten. Je mapt en filtert je data een aantal keer, misschien kun je deze functies uit je server file halen.

Je templates zien er netjes uit. Goed verdeeld.

Lekker bezig geweest deze week, volgende week verder met een service worker!

**Comment by standrd** [comment]
Hoi Robin,

ondertussen heb ik mijn readme geupdatet met jouw feedback, en ook de code opgeschoont zoals je voorstelde. Thanks!
